### ISSUE TITLE
Package with id {id} does not exist

### ISSUE THREAD

**Issue by jnozsc** [fadmaa/grefine-ckan-storage-extension#2]
I build and run this extension under google refine 2.6(trunk version), I meet same error as 
package with id {package id} doest not exist on http://localhost/api/rest/package

``` bash
11:44:21.944 [                   refine] POST /command/ckan-storage-extension/upload-to-ckan (15ms)
11:44:22.245 [                  command] Exception caught (301ms)
java.lang.RuntimeException: Package with id testgood does not exist on http://localhost/api/rest/package
    at com.google.refine.net.ckan.CkanApiProxy.addGroupOfResources(CkanApiProxy.java:116)
    at com.google.refine.net.ckan.storage.commands.UploadToCKANCommand.doPost(UploadToCKANCommand.java:87)
    at com.google.refine.RefineServlet.service(RefineServlet.java:179)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

but when I use the archive binary files in google refine 2.5, I meet another error times and times

``` bash
failed to upload file to CKAN Storage. A wrong API key maybe? 
```

Do I forget any necessary configuration on my local ckan server?  

In fact, the packaged extension can create new dataset to my local ckan server, but it won't upload the content of the dataset to my local server. It just create a empty dataset.

So I guess there is some hard coding issue in this extension. I really want to fix this, but right now, I even cannot build this extension successfully as you did.

Could you pay a little attention and investigate this tiny issue? 

Thank you.

**Comment by fadmaa** [comment]
I fixed the .classpath and fixed a couple of URIs to point to datahub.io now
Please try it and let me know if it works

**Comment by jnozsc** [comment]
Thanks for updating.

no more

```
package with id {package id} doest not exist on http://localhost/api/rest/package
```

error, <b>BUT still</b> get

```
failed to upload file to CKAN Storage. A wrong API key maybe? 
```

error message.

I guess the problem is, your extension try to upload every files to <b>datahub.io, even if the user change the api base URL in the extension's pop-up window</b>

That's what I mention before 'the hard coding' issue.

**Comment by jnozsc** [comment]
for example, in the file

``` bash
/src/com/google/refine/net/ckan/StorageApiProxy.java
```

the line 87, 88

``` Java
private static final String CKAN_STORAGE_BASE_URI = "http://ckan.net/api/storage";
private static final String CKAN_STORAGE_FILES_BASE_URI = "http://ckan.net/storage/f/";
```

why declare CKAN_STORAGE_BASE_URI and CKAN_STORAGE_FILES_BASE_URI as<b> final</b> variables?
I guess maybe there is some relationship between the bug I met and these codes

**Comment by fadmaa** [comment]
Are you using your own deployment of CKAN Storage? If so, try changing the URIs in the source code and see if it works.

**Comment by jnozsc** [comment]
yes, I install a local CKAN server at http://localhost/
that's why I want to change the URL in the extension's pop-up window.

I have tried to modify 

the line 87, 88

``` java
private static final String CKAN_STORAGE_BASE_URI = "http://ckan.net/api/storage";
private static final String CKAN_STORAGE_FILES_BASE_URI = "http://ckan.net/storage/f/";
```

to

``` java
private static final String CKAN_STORAGE_BASE_URI = "http://localhost/api/storage";
private static final String CKAN_STORAGE_FILES_BASE_URI = "http://localhost/storage/f/";
```

but I still get the error message:

```
failed to upload file to CKAN Storage. A wrong API key maybe? 
```

and then I check my local CKAN server, this extension can only create a new empty dataset, but not upload the data to the server. That's the problem

**Comment by jnozsc** [comment]
the error log as following

```
09:47:14.205 [                   refine] POST /command/ckan-storage-extension/upload-to-ckan (45226ms)
09:47:14.933 [                  command] Exception caught (728ms)
java.lang.RuntimeException: failed to upload file to CKAN Storage. A wrong API key maybe? 
    at com.google.refine.net.ckan.StorageApiProxy.uploadFile(StorageApiProxy.java:81)
    at com.google.refine.net.ckan.CkanApiProxy.addGroupOfResources(CkanApiProxy.java:141)
    at com.google.refine.net.ckan.storage.commands.UploadToCKANCommand.doPost(UploadToCKANCommand.java:87)
    at com.google.refine.RefineServlet.service(RefineServlet.java:179)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 6 [character 5 line 2]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:423)
    at org.json.JSONObject.<init>(JSONObject.java:184)
    at org.json.JSONObject.<init>(JSONObject.java:311)
    at com.google.refine.net.ckan.StorageApiProxy.uploadFile(StorageApiProxy.java:40)
    ... 25 more

```

**Comment by jnozsc** [comment]
since the exception is localtion at

storgageApiProxy.java

``` java
catch(JSONException je){
            throw new RuntimeException("failed to upload file to CKAN Storage. A wrong API key maybe? ",je);
```

the JSON parse part in this file is 

``` java
//now parse JSON
JSONObject obj = new JSONObject(os.toString());

//post the file now
String uploadFileUrl = obj.getString("action");
HttpPost postFile = new HttpPost(uploadFileUrl);
postFile.setHeader("Authorization", apikey);
MultipartEntity mpEntity = new MultipartEntity(HttpMultipartMode.STRICT);

JSONArray fields = obj.getJSONArray("fields");
for(int i=0;i<fields.length();i++){
    JSONObject fieldObj = fields.getJSONObject(i);
    String fieldName = fieldObj.getString("name");
    String fieldValue = fieldObj.getString("value");
    if(fieldName.equals("key")){
        filekey = fieldValue;
    }
    mpEntity.addPart(fieldName, new StringBody(fieldValue,"multipart/form-data",Charset.forName("UTF-8")));
}       
```

so I think the error maybe is related with this part.

Well, maybe your find it is not easy to install CKAN on local machine to test.
My suggestion is use VMware and install ubuntu and then follow this instruction 
http://docs.ckan.org/en/latest/install-from-package.html

I have successfully installed CKAN on ubuntu 13.04, if you have any problem when you install CKAN, please contact me

**Comment by jnozsc** [comment]
any update?

**Comment by fadmaa** [comment]
late update am afraid but better than none... updated the extension, it'd be great if you can test it
